#!/bin/bash

echo "Replacing the default Passenger server with Puma"

pushd ${OPENSHIFT_REPO_DIR} > /dev/null

${HOME}/ruby/bin/control stop

set -e

PUMA_PID_FILE="${OPENSHIFT_DATA_DIR}puma.pid"
PUMA_BIND_URL="tcp://${OPENSHIFT_RUBY_IP}:${OPENSHIFT_RUBY_PORT}"
PUMA_OPTS="-d --pidfile ${PUMA_PID_FILE} -e production --bind '${PUMA_BIND_URL}'"

bundle exec "puma $PUMA_OPTS"

exit 0
